# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedmineCli < Formula
  desc "Redmine CLI - Redmine REST API を操作する CLI ツール"
  homepage "https://github.com/chippy-ao/redmine-cli"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.0.0/redmine-cli_darwin_amd64.tar.gz"
      sha256 "cd373bd3d4f891702ad9f7d155856dd806d814bf3d8acb628258bea7ecb323a2"

      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.0.0/redmine-cli_darwin_arm64.tar.gz"
      sha256 "72c0751d16e0835b540944ed17904740ce433ef60cea6117a8fb536ebf1becef"

      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.0.0/redmine-cli_linux_amd64.tar.gz"
      sha256 "f43e901218560b0bbef75824fcc138299ad69ae92b595a1f9d91c3e5f96e4471"
      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.0.0/redmine-cli_linux_arm64.tar.gz"
      sha256 "468ca1184bcc0f273cb5f605d5eab195b3c84f4843430e031c1566321494c27f"
      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
  end
end
