# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedmineCli < Formula
  desc "Redmine CLI - Redmine REST API を操作する CLI ツール"
  homepage "https://github.com/chippy-ao/redmine-cli"
  version "2.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.3.0/redmine-cli_darwin_amd64.tar.gz"
      sha256 "684ae63908225853e49f87aa586d5e0ebe9c061555eaa743a1683a74b6d1c057"

      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.3.0/redmine-cli_darwin_arm64.tar.gz"
      sha256 "38ba0a7e8d7e4786dbc7a2997b44c7a0c1f05113997fed0991cd115405a675e4"

      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.3.0/redmine-cli_linux_amd64.tar.gz"
      sha256 "7c87d8f5a21136888fff40e02d4222b7ea407a1d379c20f35ab3b4c32cb6b5b6"
      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chippy-ao/redmine-cli/releases/download/v2.3.0/redmine-cli_linux_arm64.tar.gz"
      sha256 "50d3580969dc66c3340c555d43a4d8231c6df9e5dde3e134fdb2937317bc0fe9"
      define_method(:install) do
        bin.install "redmine-cli"
      end
    end
  end
end
